### ISSUE TITLE
Projeto não compila

### ISSUE THREAD

**Issue by horaciorem** [MonkeyNights/monkey-hub-app#2]
Olá, o projeto android não compila.

Já tentei limpar todas as referências e adicionar de novo, dar clean, rebuild, baixar os pacotes de novo, mudar a versão do sdk, nada resolve.

Obrigado.

![capture](https://cloud.githubusercontent.com/assets/25616037/25588289/122691b4-2e7e-11e7-9dee-9040c2d6ce53.PNG)

**Comment by sdifiore** [comment]
Otavio, depois de muito brigar com o emulador Android, a melhor alternativa que encontrei para acompanhar o treinamento foi usando a UWP... Se vc estiver executando em Windows, testa no próprio Windows, que inclusive é bem mais rápido...

**Comment by heytherewill** [comment]
@otavioremedio, um dos erros acontece pelo mesmo motivo que está descrito [aqui](https://github.com/MonkeyNights/xamarin-teste-seu-ambiente/issues/30). Verifique se corrigindo isso seu projeto irá compilar novamente e reporte o resultado aqui.

**Comment by horaciorem** [comment]
Resolvido, era só o tamanho do caminho realmente. Valeu!!!
